### PR TITLE
Refactored Linters

### LINKED ISSUE #5: Add Linter
Create Github Actions for following Linter

- [x] Python
- [x] JavaScript

### PR DESCRIPTION
**Pull request by iamrajiv**
#### References to other Issues or PRs
Fixes #5 #7

#### Have you read the [Contributing Guidelines](https://github.com/BITSoC/livestream/blob/master/CONTRIBUTING.md)?
Yes

#### Brief description of what is fixed or changed
Refactored Existing Linters

### CODE REVIEW

**Comment by iamrajiv** [comment]
@SKAUL05 Please review

**Review by SKAUL05 — CHANGES_REQUESTED** [review]
Change Names of GitHub Actions to following
Black Test
ESLint Test
Flake8 Test

**Comment by iamrajiv** [comment]
@SKAUL05 Please review

**Comment by SKAUL05** [comment]
> @SKAUL05 Please review

You can re request review instead of typing..

**Comment by iamrajiv** [comment]
@SKAUL05 Sure, I forgot that feature :sweat_smile:

**Review by SKAUL05 — APPROVED** [review]

**Pull request merged**
