### PR TITLE
Added Linters for JavaScript and Python

### LINKED ISSUE #5: Add Linter
Create Github Actions for following Linter

- [x] Python
- [x] JavaScript

### PR DESCRIPTION
**Pull request by iamrajiv**
Fixes: #5

### CODE REVIEW

**Comment by SKAUL05** [comment]
Change the file name to eslint or jslint.

**Comment by iamrajiv** [comment]
@SKAUL05 should I make  separate `linter.yml` file for javascript and python or should add both the linter jobs in same `.yml` file

**Comment by SKAUL05** [comment]
Make separate ones for all 3
EsLint
Flake8
Black
It will help us to figure out at what stage Lint is failing.

**Comment by iamrajiv** [comment]
@SKAUL05 Please review

**Review by SKAUL05 — APPROVED** [review]

**Comment by SKAUL05** [comment]
@iamrajiv All Lints are failing. Pls Check it. I have merged this PR. Check the Lints that are failing and create new PR with required Changes.
Specify properly what each file does, there are 2 similar files `eslint.yml` and `lint.yml`

**Pull request merged**
