### PR TITLE
Added pull request template and issue template

### LINKED ISSUE #8: Adding pull request template and issue template
Reference: https://docs.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates

### PR DESCRIPTION
**Pull request by iamrajiv**
Fixes: #8

### CODE REVIEW

**Comment by iamrajiv** [comment]
@SKAUL05 please review

**Comment by SKAUL05** [comment]
@iamrajiv Add appropriate labels.

**Review by SKAUL05 — CHANGES_REQUESTED** [review]
**ISSUE_TEMPLATE** : Add General Instructions for BitSoc Candidates as mentioned in Zulip for raising an issue.

**Comment by iamrajiv** [comment]
@SKAUL05 I am not able to add labels. I think I don't have permission to do that.

**Review by SKAUL05 — APPROVED** [review]
@iamrajiv Looks Good

**Pull request merged**
