### PR TITLE
Refactored Linters

### LINKED ISSUE #5: Add Linter
Create Github Actions for following Linter

- [x] Python
- [x] JavaScript

### PR DESCRIPTION
**Pull request by iamrajiv**
Refactored Flake8 and Black Linters and removed duplicate Linters.
Fixes: #5 #7

### CODE REVIEW

**Comment by iamrajiv** [comment]
@SKAUL05 Please review

**Review by SKAUL05 — CHANGES_REQUESTED** [review]
Black is still failing

**Comment by iamrajiv** [comment]
@SKAUL05 Please review

**Comment by iamrajiv** [comment]
@SKAUL05 Please review

**Review by SKAUL05 — CHANGES_REQUESTED** [review]
11 commits are hard to review. Please rebase.

**Review by SKAUL05 — COMMENTED** [review]
What does `black.yml` check. Does it run black on whole repo or only on the files in current PR.

**Comment by iamrajiv** [comment]
@SKAUL05 Black run on whole master branch whenever there is a pull request.

**Comment by SKAUL05** [comment]
Black Lint while running is showing no python files found.
Could u check that why it is showing that.
Check ESLint also, it is bypassing Run step.

**Comment by iamrajiv** [comment]
@SKAUL05 Please review

**Review by SKAUL05 — CHANGES_REQUESTED** [review]
- Checkout files `.DS_Store` and `.github/.DS_Store`.
- ESLint still skipping the run part.
- Rebase PR

**Comment by iamrajiv** [comment]
@SKAUL05 I am closing this PR because there is a conflict with the file in my local system, sorry for the inconvenience. I will be making a new PR.

**Pull request closed without merging**
